services:
  db:
    container_name: "postgres"
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    environment:
      - POSTGRES_PASSWORD=cadueUHulyGUxP
      - POSTGRES_USER=postgres
      - POSTGRES_DB=my_django_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d my_django_db" ]
      interval: 5s
      timeout: 5s
      retries: 5


  django:
    container_name: "django"
    build:
      context: ../backend
    command: >
      bash -c '
      python3 manage.py makemigrations &&
      python3 manage.py migrate --no-input &&
      python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - ../backend/:/code
    ports:
      - "8003:8000"
    depends_on:
      - db
    networks:
      - nginx_network
      - backend_network
    env_file: "../.env"

  vue:
    build:
      context: ../frontend
      dockerfile: Dockerfile-vue-dev
    extra_hosts:
      - "*.vandiest.it:127.0.0.1"
    volumes:
      - .:/app/frontend
    ports:
      - "8081:8080"
    networks:
      - nginx_network
    depends_on:
      - db

networks:
  backend_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  postgres_data:

