services:
  db:
    container_name: "postgres"
    image: postgres
    restart: always
    ports:
      - '5432-5432'
    networks:
      - backend_network
    environment:
      - POSTGRES_PASSWORD=SUPERSECRETPA$$WORD

  django:
    container_name: "django"
    build:
      context: ../backend/mysite2
    command: >
      bash -c '
      python3 manage.py makemigrations &&
      python3 manage.py migrate --no-input &&
      python3 manage.py runserver 0.0.0.0:8000'
    env_file:
      - ../backend/.env
    volumes:
      - ../backend/mysite2:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - nginx_network
      - backend_network
  

networks:
  backend_network:
    driver: bridge
  nginx_network:
    driver: bridge

