services:
  db:
    container_name: "postgres"
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    environment:
      - POSTGRES_PASSWORD=cadueUHulyGUxP
      - POSTGRES_USER=postgres
      - POSTGRES_DB=my_django_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d my_django_db" ]
      interval: 5s
      timeout: 5s
      retries: 5


  django:
    container_name: "django"
    build:
      context: ../backend
    command: >
      bash -c '
      python3 manage.py makemigrations &&
      python3 manage.py migrate --no-input &&
      gunicorn info.wsgi -b 0.0.0.0:8001'
    volumes:
      - ../backend/:/code
    depends_on:
      - db
    networks:
      # - nginx_network
      - backend_network
    env_file: "../.env"

  nginx:
    container_name: "nginx"
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - django
      - db 
    networks:
      - nginx_network

networks:
  backend_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  postgres_data:
