services:
  db:
    container_name: "postgres"
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    environment:
      - POSTGRES_PASSWORD=cadueUHulyGUxP
      - POSTGRES_USER=postgres
      - POSTGRES_DB=my_django_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d my_django_db" ]
      interval: 5s
      timeout: 5s
      retries: 5


  django:
    container_name: "django"
    build:
      context: ../backend
    command: >
      bash -c '
      python3 manage.py makemigrations &&
      python3 manage.py migrate --no-input &&
      python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - ../backend/:/code
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
    networks:
      - backend_network
    env_file: "../.env"

  vue:
    build:
      context: ../frontend
      dockerfile: Dockerfile-vue-dev
#    volumes:
#      - ../frontend:/app/frontend:cached
#      - /app/node_modules
    develop:
      watch:
        # Sync the entire frontend directory when other file changes
        - action: sync
          path: ../frontend
          target: /app
          ignore:
            - node_modules
        # Rebuild the app container when package.json changes
        - action: rebuild
          path: ../frontend/package.json
          target: /app/package.json
        # Sync and restart the container when the vite.config.js file changes
        - action: sync+restart
          path: ../frontend/vite.config.js
          target: /app/vite.config.js
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "127.0.0.1:5173:5173"
    networks:
      - backend_network
    depends_on:
      - db

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:

